- lib/active_record_doctor/tasks/extraneous_indexes.rb
I've noticed you're using `map(...).flatten(1)` idiom, which isn't optimal.
Please find attached benchmark results and maybe consider using `flat_map` for better performance :)
```
require 'benchmark/ips'
ARRAY = (1..100).to_a
def slow_flatten_1
ARRAY.map { |e| [e, e] }.flatten(1)
end
def slow_flatten
ARRAY.map { |e| [e, e] }.flatten
end
def fast
ARRAY.flat_map { |e| [e, e] }
end
Benchmark.ips do |x|
x.report('Array#map.flatten(1)') { slow_flatten_1 }
x.report('Array#map.flatten')    { slow_flatten   }
x.report('Array#flat_map')       { fast           }
x.compare!
end
```
(https://github.com/JuanitoFatas/fast-ruby/blob/master/code/enumerable/map-flatten-vs-flat_map.rb)
Run on my machine (1,4 GHz Intel Core i5, 4 GB 1600 MHz DDR3):
```
Calculating ------------------------------------- …
```
> Improve performance by using flat_map

- README.md
Before, the numbered lists would restart their numbering in the middle.
After, the numbered lists continue to increase the number.
> Fix issues with numbered lists in README when rendered.

- lib/active_record_doctor/tasks/extraneous_indexes.rb
ActiveRecord::ConnectionAdapters::IndexDefinition#columns returns a
String in the case of PostgreSQL full-text indexes, e.g.:
"to_tsvector('english'::regconfig, (first_name)::text)"
So those can be skipped for this analyzer.  Otherwise we get
ArgumentError: wrong number of arguments (given 0, expected 1+)
exceptions from ExtraneousIndex#prefix?.
> Extraneous index check can skip fulltext indexes

- gemfiles/Gemfile.rails-5.2.x
This PR is about fixing the build for Rails 5.2 on Ruby 2.2.10.
The released gem has a "safe navigation" in it. That's a 2.3 feature. 
The problem:
```
rake aborted!
SyntaxError: /home/travis/.rvm/gems/ruby-2.2.10/gems/actionpack-5.2.4.2/lib/action_dispatch/request/session.rb:96: syntax error, unexpected '.'
id&.public_id
^
```
> Use Rails 5-2-stable branch to support Ruby 2.2.10

- active_record_doctor.gemspec
- lib/active_record_doctor/tasks.rb
ruby:2.7.1
rails:6.0.2.2
```
/usr/src/app # rails active_record_doctor
rails aborted!
NoMethodError: undefined method `subclasses' for ActiveRecordDoctor::Tasks::Base:Class
Did you mean?  superclass
/usr/local/bundle/gems/active_record_doctor-1.7.1/lib/active_record_doctor/tasks.rb:4:in `all'
/usr/local/bundle/gems/active_record_doctor-1.7.1/lib/tasks/active_record_doctor.rake:29:in `block in <main>'
/usr/local/bundle/gems/active_record_doctor-1.7.1/lib/tasks/active_record_doctor.rake:12:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:70:in `load'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:70:in `rescue in load'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core …
```
> Fix undefined method subclasses

- lib/active_record_doctor/tasks/unindexed_deleted_at.rb
- test/active_record_doctor/tasks/unindexed_deleted_at_test.rb
> [paranoia](https://github.com/rubysherpas/paranoia) has some surprising behaviour (like overriding ActiveRecord's delete and destroy) and is not recommended for new projects. See [discard's README](https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid) for more details.
Add both `deleted_at` and `discarded_at` to the recipe.
Closes #42
> Add support of discarded_at to unindexed_deleted_at task

- .gitignore
- .travis.yml
- Rakefile
- gemfiles/Gemfile.rails-5.0.x
- gemfiles/Gemfile.rails-5.1.x
- gemfiles/Gemfile.rails-5.2.x
- gemfiles/Gemfile.rails-6.0.x
- gemfiles/Gemfile.rails-6.1.x
- test/setup.rb
I think, this is a small, but still valuable improvement. 
I personally forgot several times that we always need to set `DATABASE` variable when testing, and many more times if this should be "postgresql" or just "postgres"? 😄
Maybe even better as:
```ruby
when /postgres/i
when /mysql/i
```
> Rework testing rake tasks

- lib/generators/active_record_doctor/add_indexes/add_indexes_generator.rb
Before, running the generator breaks since 50c1191100 due to the mention
of an undefined `version` method.
This commit uses Migration subclasses as Rails does (see https://github.com/rails/rails/commit/6940dc860c4b25bff2eded370f2af4316de15a30)
I'd be happy to work in a separate PR on tests for the existing generator, and introducing others.
Is there any plans related or work already started I can help with @gregnavis?
> Fix AddIndexesGenerator migration versioning

- lib/generators/active_record_doctor/add_indexes/add_indexes_generator.rb
- test/generators/active_record_doctor/add_indexes/add_indexes_generator_test.rb
To prevent exceptions like
```
StandardError: An error has occurred, all later migrations canceled:
Index name 'index_deleted_subscriber_invoice_status_transitions_on_subscriber_invoice_id' on table 'deleted_subscriber_invoice_status_transitions' is too long; the limit is 64 characters
```
we should suggest shorter name
> Use shorter name if index name is too long

- lib/active_record_doctor/config/default.rb
- lib/active_record_doctor/detectors/missing_non_null_constraint.rb
- test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
When using STI, models share the same table and we should generate a warning only for a parent class.
Fixes #73
> Ignore STI models in MissingNonNullConstraint detector

- lib/generators/active_record_doctor/add_indexes/add_indexes_generator.rb
`allowed_index_name_length` [was removed from rails](https://github.com/rails/rails/pull/39083).
In reality, whoever implemented this class and used that method some time ago, should be used `index_name_length`, because this is the correct method.
> allowed_index_name_length is removed from Rails 7.0

- lib/active_record_doctor/detectors/short_primary_key_type.rb
- test/active_record_doctor/detectors/short_primary_key_type_test.rb
This PR fixes this CI failure - https://github.com/gregnavis/active_record_doctor/runs/4775054306?check_suite_focus=true#step:6:20
And also adds a check for `uuid` primary key type to `ShortPrimaryKeyType`. It was added before (https://github.com/gregnavis/active_record_doctor/commit/a96e26b08dde0d1e98ca196ea0f5b50be3798e1f#diff-b462e6b0c496090ec5749009df0892da4ba6cf3d25ec16fa19269191bf10686eR10), seems like you accidentally removed it.
> Accept uuid as long primary key type

- README.md
It looks like the correct configuration option according to the tests is `ignore_attributes`.
Source:
https://github.com/gregnavis/active_record_doctor/blob/32906dc95f4343290c237026596a535c7348351f/test/active_record_doctor/detectors/missing_presence_validation_test.rb#L153-L168
> Fix typo in Missing Presence Validations config options

- lib/active_record_doctor/detectors/base.rb
- lib/active_record_doctor/detectors/missing_non_null_constraint.rb
- lib/active_record_doctor/detectors/missing_presence_validation.rb
- test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
- test/active_record_doctor/detectors/missing_presence_validation_test.rb
Closes #83
While technically mysql/mariadb, sqlite3 and some others support check constraints, I have seen this trick is only applied to postgres databases, as commented in the issue. So added a raw query for rails < 6.1 only for postgres, to make the implementation simple. 
`if connection.respond_to?(:supports_check_constraints?) && connection.supports_check_constraints?` branch should cover everything else.
@owst
> Accept NOT NULL check constraints for `MissingNonNullConstraint` detector

- lib/active_record_doctor/detectors/unindexed_deleted_at.rb
- test/active_record_doctor/detectors/unindexed_deleted_at_test.rb
The user will choose to add index to quickly get deleted items by some criteria: `add_index :users, :email, where: "deleted_at IS NOT NULL"`. 
We should accept this, because otherwise `WHERE deleted_at IS NOT NULL AND deleted_at IS NULL` does not make sense.
> Accept `deleted_at IS NOT NULL` partial indexes for unindexed_deleted_at

- lib/active_record_doctor/detectors/missing_presence_validation.rb
- test/active_record_doctor/detectors/missing_presence_validation_test.rb
Rails also sets automatically `created_on/updated_on` columns when `created_at/updated_at` are missing. https://github.com/rails/rails/blob/be400c3ca2b86111766d840979478fc026679368/activerecord/lib/active_record/timestamp.rb#L82-L88
> Ignore created_on/updated_on for missing_presence_validation

- lib/active_record_doctor/detectors/incorrect_length_validation.rb
- test/active_record_doctor/detectors/incorrect_length_validation_test.rb
While checking each column for length validations in the model, the column name is not considered. By not doing this, the first model validation will be the one setting the conditions  for all columns in the schema.
> Check column name in length validators

- lib/active_record_doctor/detectors/base.rb
- lib/active_record_doctor/detectors/undefined_table_references.rb
We can avoid creating our own method to get the VIEWs, since `data_source_exists?` already does this. And additionally this will allow for models to be backed by foreign tables in PostgreSQL.
https://github.com/rails/rails/blob/be400c3ca2b86111766d840979478fc026679368/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L882-L909
> Allow models to be backed by foreign tables in PostgreSQL for undefined_table_references

- README.md
It does not exist `ignore_columns` at `incorrect_dependent_option`, instead of it the correct one is `ignore_associations`
> fix: no exists `ignore_columns` at `incorrect_dependent_option`

- .rubocop.yml
- lib/active_record_doctor/detectors/mismatched_foreign_key_type.rb
- test/active_record_doctor/detectors/mismatched_foreign_key_type_test.rb
Imagine you have two tables `companies` and `users` like the following
Let's say that, for some reason, you need to create an FK on the `entity_id` column connecting both tables
Considering the column in the referenced table is unique it works quite fine in terms of Database but, if you run AR Doctor on a project with these tables the result will be:
`users.entity_id references a column of a different type - foreign keys should be of the same type as the referenced column`
That's because it currently compares the FK column with the PK of the referenced table and not the column the FK refers to.
This PR intends to fix it by fetching the column based on the FK referenced column instead.
> Correctly check column types when FK refers to non-PK column

- lib/active_record_doctor/detectors/base.rb
- lib/active_record_doctor/detectors/extraneous_indexes.rb
- test/active_record_doctor/detectors/extraneous_indexes_test.rb
Just found an extra index on the materialized view in my codebase.
Theoretically, other detectors, like `UnindexedForeignKeys` and `UnindexedDeletedAt` can be easily extended to handle materialized views too, but I think the case with extra indexes is the most popular.
> Detect extraneous indexes on PostgreSQL materialized views

- lib/active_record_doctor/detectors/short_primary_key_type.rb
- test/active_record_doctor/detectors/short_primary_key_type_test.rb
It is possible the user uses other types for primary keys, for example string `username` for `users` table, or client side generated uuid-like strings for some other tables, or external ids (like `stripe_id` string) for `stripe_users` table, etc.
> Ignore non-integer and non-uuid primary keys for short_primary_key_type

- lib/active_record_doctor.rb
- lib/active_record_doctor/detectors/base.rb
- lib/active_record_doctor/detectors/missing_unique_indexes.rb
- lib/active_record_doctor/utils.rb
- test/active_record_doctor/detectors/missing_unique_indexes_test.rb
Case insensitivity in uniqueness validations was skipped in this gem, but this is a very popular problem. 
I remember I was trapped by this at least once. And there is even [a related article from Richard Scheeman](https://schneems.com/2017/07/18/how-i-reduced-my-db-server-load-by-80/) with his investigation of the performance problems on production with his findings.   
It adds some ugly columns parsing, but I think we can deal with it.
> Detect missing unique lowercase indexes for case insensitive unique validations

- lib/active_record_doctor/detectors/unindexed_foreign_keys.rb
- test/active_record_doctor/detectors/unindexed_foreign_keys_test.rb
`UnindexedForeignKeys` currently checks only for columns named like `_id`. In most cases, these really are (or acting like without real db `FOREIGN KEY` constraint) foreign key columns. 
But this detector misses real unindexed foreign keys with non-standard names.
> Enhance `UnindexedForeignKeys` to check for non-standard named foreign keys

- lib/active_record_doctor/detectors/unindexed_foreign_keys.rb
- lib/generators/active_record_doctor/add_indexes/add_indexes_generator.rb
- test/active_record_doctor/detectors/unindexed_foreign_keys_test.rb
- test/generators/active_record_doctor/add_indexes/add_indexes_generator_test.rb
Accept polymorphic foreign key-like columns which are a prefix of a larger index. Previously, only exact match on index columns was made.
> Enhance handling of polymorphic foreign key-like columns in `UnindexedForeignKeys`

- lib/active_record_doctor.rb
Fixes https://github.com/gregnavis/active_record_doctor/issues/134.
> Fix loading `ActiveRecordDoctor::Rake::Task` for non rails projects

- lib/active_record_doctor/detectors/extraneous_indexes.rb
- test/active_record_doctor/detectors/extraneous_indexes_test.rb
Student was confused by the wording, figured I'd clear it up for others.
> Suggesting a better message

- lib/active_record_doctor/detectors/extraneous_indexes.rb
- test/active_record_doctor/detectors/extraneous_indexes_test.rb
I recently tested this gem on a project which has quite a few matviews in the database and a foreign wrapper for MySQL, but still is using `schema.rb` without dumped them there (don't ask why). And when `extraneous_indexes` reported extra indexes, it hasn't mentioned where these indexes are defined, so it was quite a challenge to find it through `psql`. This PR simplifies such debugging for future users.
> Include table name in the message for `extraneous_indexes`

- lib/active_record_doctor/detectors/base.rb
- lib/active_record_doctor/detectors/missing_unique_indexes.rb
- test/active_record_doctor/detectors/missing_unique_indexes_test.rb
Currently, `missing_unique_indexes` reports an offense for both a parent and a child in the STI. This also requires a config to be added for both of them, if you want to ignore this offense.
> Ignore inherited validations and associations in STI models for `missing_unique_indexes`

- lib/active_record_doctor/detectors/extraneous_indexes.rb
- test/active_record_doctor/detectors/extraneous_indexes_test.rb
ActiveRecord returns `columns` for expression indexes as a string and `columns.count` raises an argument error, since is called on a string.
> Fix `extraneous_indexes` for expression indexes

- lib/active_record_doctor/detectors/missing_unique_indexes.rb
- test/active_record_doctor/detectors/missing_unique_indexes_test.rb
> Fix `missing_unique_indexes` detector's `ignore_columns` config for `has_one` associations

- lib/active_record_doctor/detectors/unindexed_foreign_keys.rb
- test/active_record_doctor/detectors/unindexed_foreign_keys_test.rb
> Fix a false positive for `unindexed_foreign_keys` when having foreign key on a primary key column

- lib/active_record_doctor/detectors/missing_unique_indexes.rb
- test/active_record_doctor/detectors/missing_unique_indexes_test.rb
https://github.com/gregnavis/active_record_doctor/pull/157#issuecomment-1824759221
> Fix a false positive for `unique_indexes` when `has_one` on a primary key column

- lib/active_record_doctor/detectors/extraneous_indexes.rb
- test/active_record_doctor/detectors/extraneous_indexes_test.rb
Rails 7.1 will have support for PostgreSQL `INCLUDE` indexes - https://github.com/rails/rails/pull/44803. If you are ok with this PR changes, we can wait when the new rails version is released or can merge earlier, since some people are running on some sort of rails head and will already benefit from this.
This gem's CI is not testing against rails head, so the newly added tests are skipped currently.
> Support PostgreSQL `INCLUDE` indexes in `ExtraneousIndexes` checker

- README.md
- lib/active_record_doctor/config/default.rb
- lib/active_record_doctor/detectors/missing_presence_validation.rb
- test/active_record_doctor/detectors/missing_presence_validation_test.rb
Fixes #170.
We can add a flag for this behaviour to the checker, but I do not think this will be needed, as this looks like a legit use case for all the cases.
> missing_presence_validation: ignore columns with defaults

- README.md
- lib/active_record_doctor/config/default.rb
- lib/active_record_doctor/detectors/base.rb
- lib/active_record_doctor/detectors/missing_unique_indexes.rb
- test/active_record_doctor/detectors/missing_unique_indexes_test.rb
This commit enhances the missing_unique_index detector by making it aware of `has_and_belongs_to_many` associations, in addition to `has_one` associations and uniqueness validations.
This case is very often overlooked and leads to duplicates in the database or/and some unnecessary code to deal with duplicates.
I tried to imagine the case when duplicates would be useful, but was unable to do so. Instead I was able to google a couple of posts with people ranting ([example1](http://spoolz.com/2014/05/20/rails-habtm-with-unique-scope-and-select-columns/), [example2](https://www.semicolonandsons.com/code_diary/databases/has-and-belongs-to-many-tables-often-need-unique-indexes)) and suggesting to add unique indexes on it.
> Expect unique indexes on `has_and_belongs_to_many` associations

- lib/active_record_doctor/detectors/missing_non_null_constraint.rb
- test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
When the STI-like parent model has no children, all the `next` branches in the `detect` method pass (specifically `next if !concrete_models.all? { |model| non_null_needed?(model, column) }`) and `MissingNonNullConstraint` erroneously adds offenses for the column. See a test case for the example.
> Fix `missing_non_null_constraint` when there are no STI children for STI-like parent

- lib/active_record_doctor/detectors/base.rb
- test/active_record_doctor/detectors/incorrect_boolean_presence_validation_test.rb
I wasted some time figuring out why class names are not working for `:ignore_models` to find out, that it accepts only strings. I think accepting classes we will improve UX a bit.
> Accept classes in `:ignore_models` configuration

- README.md
The configuration is `ignore_indexes` not `ignore_columns`.
See https://github.com/gregnavis/active_record_doctor/blob/4ee897cac9d1aea7d91e28f0e3d98dcb13922405/lib/active_record_doctor/detectors/extraneous_indexes.rb#L14
> Fix configuration option key in README

- lib/active_record_doctor/detectors/missing_unique_indexes.rb
- lib/active_record_doctor/utils.rb
- test/setup.rb
> Fix checking for expression indexes support

- lib/active_record_doctor/detectors/missing_non_null_constraint.rb
- test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
> missing_non_null_constraint: ignore presence validations with specific context

- lib/active_record_doctor/detectors/missing_non_null_constraint.rb
- test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
Once the timestamps columns are established on a table, they might as well be NOT NULL to enforce their existence. All ActiveRecord operations set these values so they will always exist under normal usage.
Fixes #184
> Check timestamp columns (created_at, updated_at) are NOT NULL

- lib/active_record_doctor/detectors/missing_foreign_keys.rb
- test/active_record_doctor/detectors/missing_foreign_keys_test.rb
The `missing_foreign_keys` checker does not currently consider the type of the column and so strings, booleans etc are marked as bad. 
We currently muted 100+ cases and 100% of these cases are false positives. I think it is reasonable to consider only integer-like and uuid columns. It is possible someone uses a string column as a foreign key, but I expect this to happen in 0.001% cases and it is better to miss this, than the need to pollute the config file with a bunch of ignores.
> missing_foreign_keys: consider column type for foreign key candidates

- lib/active_record_doctor/detectors/incorrect_dependent_option.rb
- test/active_record_doctor/detectors/incorrect_dependent_option_test.rb
> Fix incorrect_dependent_option checker for broken associations

- lib/active_record_doctor/detectors/missing_presence_validation.rb
- test/active_record_doctor/detectors/missing_presence_validation_test.rb
This check produces false positives for counter cache columns. 
These are expected to be set by ActiveRecord, not by users.
> missing_presence_validation: ignore counter cache columns

- active_record_doctor.gemspec
- lib/active_record_doctor/detectors/missing_non_null_constraint.rb
- test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
> missing_non_null_constraint: ignore database views

- lib/active_record_doctor/detectors/base.rb
- lib/active_record_doctor/detectors/missing_foreign_keys.rb
- lib/active_record_doctor/detectors/unindexed_foreign_keys.rb
- test/active_record_doctor/detectors/unindexed_foreign_keys_test.rb
Follow up to #204.
I realized, that unindexed_foreign_keys checker should do the same.
> unindexed_foreign_keys: consider column type for foreign key candidates

- lib/active_record_doctor/detectors/missing_presence_validation.rb
- test/active_record_doctor/detectors/missing_presence_validation_test.rb
Follow up to https://github.com/gregnavis/active_record_doctor/pull/171.
Forgot to also ignore default functions (like `default: -> { "CURRENT_TIMESTAMP" }`) in that PR.
> missing_presence_validation: ignore columns with default functions

- lib/active_record_doctor/detectors/missing_presence_validation.rb
- test/active_record_doctor/detectors/missing_presence_validation_test.rb
Just noticed, that `missing_presence_validation` checker marks `enum ..., validate: true` as offences, even though these are false positives. 
`enum` definition uses `validates_inclusion_of` under the hood, but the checker considers only boolean columns having proper `inclusion`/`exclusion` validations as good. I think, this should be extended to other column types.
> missing_presence_validation: ignore all columns with proper inclusion/exclusion validations

- lib/active_record_doctor/detectors/missing_presence_validation.rb
- test/active_record_doctor/detectors/missing_presence_validation_test.rb
> Fix missing_presence_validator ignoring attributes by prefix
